name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy_lambda:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - uses: actions/setup-node@v2
        with:
          node-version: '20'

      - name: Install dependencies
        run: |
          npm ci

      - name: Build and zip
        run: |
          npx ncc build index.ts # Ensure you're pointing to the correct entry file
          zip -r deploy.zip ./dist/*

      
      - name: Deploy to AWS Lambda
        run: |
          aws lambda update-function-code --function-name shoppingProducts --zip-file fileb://deploy.zip
